version: '3.4'

services:
  opendota.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5900:80"
  opendota.frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
    - opendota.api
    ports:
      - "5902:80"