version: '3.4'

services:
  opendota.api:
    image: ${DOCKER_REGISTRY-}opendotaapi
    build:
      context: .
      dockerfile: Services/ApiOpenDota/OpenDota.Api/Dockerfile

  opendota.frontend:
    image: ${DOCKER_REGISTRY-}opendotafrontend
    build:
      context: .
      dockerfile: WebApp/OpenDota.FrontEnd/Dockerfile
    